spring:
  application:
    name: qa-test
  jpa:
    hibernate:
      ddl-auto: update    # или create-drop на раннем этапе
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: health,info
qa-test:
  admin-creation-secret: "secretsecretpass"
jwt:
  secret: "x9G4kqV2Lw7cR8tZ1fM3pQ6sU9vB2nH5"
  expiration-seconds: 3600
